### PR TITLE
Update to latest mozilla-services/react-jsonschema-form

### PR DESCRIPTION
**Pull request by rasca**
I need some of the latest changes upstream so I merged master.

### CODE REVIEW

**Comment by AayushB** [comment]
^ Bump, anyone looking into this PR?

**Comment by peterkelly** [comment]
Sorry for the delays - been very busy with some other things. I will try to get to this tomorrow.

**Comment by peterkelly** [comment]
Thanks, I've just merged this now and published to npm

**Comment by rasca** [comment]
Thanks @peterkelly !

**Pull request merged**
